import {
  IsDateString,
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
  IsArray,
  ArrayMinSize,
  IsEnum,
  IsUrl,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsFutureDate } from '../../../shared/validators/is-future-date.decorator';
import { CreateTicketCategoryDto } from './create-ticket-category.dto';
import { ConcertStatus } from '../constants/concert-status.enum';

export class CreateConcertDto {
  @ApiProperty({ example: 'Anh Trai Say Hi' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  name!: string;

  @ApiPropertyOptional({ example: 'A high-energy showcase with headline performances.' })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({ example: 'District 1 Stadium, Ho Chi Minh City' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  location!: string;

  @ApiPropertyOptional({ type: [String], example: ['Phung Khanh Linh', 'Chi Dep'] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  performers?: string[];

  @ApiPropertyOptional({ example: 'Artist bio generated by AI.' })
  @IsOptional()
  @IsString()
  ai_bio?: string;

  @ApiProperty({ format: 'date-time', example: '2026-06-10T19:30:00+07:00' })
  @IsDateString()
  @IsFutureDate()
  start_time!: string;

  @ApiPropertyOptional({ example: 'https://cdn.tixora.local/maps/anh-trai-say-hi.svg' })
  @IsOptional()
  @IsString()
  @IsUrl()
  svg_map_url?: string;

  @ApiPropertyOptional({ example: 'https://cdn.tixora.local/posters/anh-trai-say-hi.png' })
  @IsOptional()
  @IsString()
  @IsUrl()
  poster_url?: string;

  @ApiProperty({ enum: ConcertStatus, example: ConcertStatus.PUBLISHED })
  @IsEnum(ConcertStatus)
  status!: ConcertStatus;

  @ApiPropertyOptional({ example: 'CONCERT', description: 'Category of concert' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  category?: string;

  @ApiPropertyOptional({ example: 'b3f572a1-2139-4dd7-897b-cf10972410a5', description: 'ID of the associated venue' })
  @IsOptional()
  @IsString()
  venue_id?: string;

  @ApiProperty({ type: [CreateTicketCategoryDto] })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreateTicketCategoryDto)
  ticketTiers!: CreateTicketCategoryDto[];
}
